version: "1.1"
pipeline:
  name: bodywork-mlflow
  docker_image: bodyworkml/bodywork-core:3.0
  DAG: server
  secrets_group: dev
stages:
  server:
    executable_module_path: mlflow_server.py
    requirements:
      - mlflow==1.16.0
      - scikit-learn
      - pyarrow
      - boto3
      - protobuf==3.20.0
      - psycopg2-binary==2.8.6
      - sentry-sdk==0.20.3
      - google-cloud-storage ==2.5.0
    secrets:
      MLFLOW_BACKEND_STORE_URI: mlflow-config
      MLFLOW_DEFAULT_ARTIFACT_ROOT: mlflow-config
      SENTRY_DSN: mlflow-config
      SERVE_ARTIFACTS: mlflow-config            #use proxy 
      AWS_ACCESS_KEY_ID: minio-credentials   
      AWS_SECRET_ACCESS_KEY: minio-credentials   
    
      # export MLFLOW_BACKEND_STORE_URI=postgresql+psycopg2://mladmin:protonflow@localhost:5433/mlflow
      # postgresql+psycopg2://mladmin:protonflow@mlflow-tracking-server-database-postgresql.default.svc.cluster.local:5433/mlflow
      # export MLFLOW_DEFAULT_ARTIFACT_ROOT=gs://proton-mlflow-artifacts
      # export SENTRY_DSN=https://497747878b804d7c84641436521454b1@sentry.proton.ai/9


    cpu_request: 1
    memory_request_mb: 250
    service:
      max_startup_time_seconds: 240
      replicas: 1
      port: 5000
      ingress: false
logging:
  log_level: INFO
